AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: LambdaEdgeRemoveTrailingSlash_20
    Description: SAM configuration for creating a Lambda@Edge function to remove trailing slashes from CloudFront requests
    Author: Si Novi
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['Lambda@Edge', 'Lambda', 'CloudFront', 'Static', 'S3']
    HomePageUrl: https://github.com/sinovi/lambda-edge-remove-trailing-slash
    SemanticVersion: 1.2.1
    SourceCodeUrl: https://github.com/sinovi/lambda-edge-remove-trailing-slash
Resources:
    LambdaEdgeRemoveTrailingSlash:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs20.x
        CodeUri: src/
        Role: !GetAtt LambdaEdgeRemoveTrailingSlashRole.Arn
        Description: 'A Lambda@Edge function to remove trailing slashes from CloudFront requests. Updated to use nodejs16.x runtime. '
        MemorySize: 128
        Timeout: 3
        AutoPublishAlias: live

    LambdaEdgeRemoveTrailingSlashRole:
      Type: "AWS::IAM::Role"
      Properties:
          Path: "/"
          ManagedPolicyArns:
              - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: "AllowLambdaServiceToAssumeRole"
                Effect: "Allow"
                Action: 
                  - "sts:AssumeRole"
                Principal:
                  Service: 
                    - "lambda.amazonaws.com"
                    - "edgelambda.amazonaws.com"
